version: "3.9"

services:
  celery:
    build:
      context: ../server/
      target: development
      dockerfile: Dockerfile
    restart: always
    command: celery -A core worker -l info
    env_file:
      - ../server/.env
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_SECRET_KEY=dj4ng0_sup3r_s3cr3t_k3y
      - DJANGO_DEBUG=1
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_BACKEND=redis://redis:6379/0
    volumes:
      - ../server/:/usr/src/app/
    depends_on:
      - db
      - redis
      - backend
      - rabbitmq

  backend:
    container_name: django
    build:
      context: ../server/
      target: development
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ../server/.env
    volumes:
      - ../server/:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_SECRET_KEY=dj4ng0_sup3r_s3cr3t_k3y
      - DJANGO_DEBUG=1
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
      - rabbitmq

  frontend:
    container_name: nextjs_container
    build:
      context: ../frontend/
      target: development
      dockerfile: Dockerfile
    restart: always
    image: nextjs_container
    volumes:
      - ../frontend/:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"

volumes:
  postgres_data:
